// Top-level build file
plugins {
    // This tells Gradle which versions to use without "applying" them to the root
    id 'com.android.application' version '8.13.2' apply false
    id 'com.android.library' version '8.13.2' apply false
    id 'org.jetbrains.kotlin.android' version '2.3.0' apply false
}