pluginManagement {
    repositories {
        google()
        mavenCentral() // Replaces jcenter() which is shut down/unreliable
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "RobotSample"
include ':app'